baseURL = 'https://kimyeonghyeon.github.io/blog/'
languageCode = 'en-us'
title = 'Research Portfolio'
theme = 'PaperMod'

[params]
env = "production"
description = "Academic researcher portfolio and publications"
author = "Your Name"

# Theme settings
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

# Profile mode
[params.profileMode]
enabled = true
title = "Your Name"
subtitle = "Research Scientist | PhD Student"
imageUrl = "profile.jpg"
imageTitle = "Profile Picture"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "Publications"
url = "/publications"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects"

[[params.profileMode.buttons]]
name = "CV"
url = "/cv.pdf"

# Social icons
[[params.socialIcons]]
name = "email"
url = "mailto:your.email@example.com"

[[params.socialIcons]]
name = "googlescholar"
url = "https://scholar.google.co.kr/citations?user=cLAlajcAAAAJ&hl=ko"

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/"

# Menu
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publications/"
weight = 20

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 30

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 40

[outputs]
home = ["HTML", "RSS", "JSON"]
